# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34fcc283cfe95a5bea754a0a67e98b802626f9071cc57a7dcaa72c24f591b62458d1e13fe1d70c8eca11a22081f0abc4d102ef93c35186f61a9db439e361d160

test:
  secret_key_base: 19d73ba6c7eb98fb9a7b73826174b4ca3b37ab2b112b2728eb064bbf845edd721fefc8d6e892cd4a462e7d46c05d42c9a99c1f44fe2651578f0c7f09037cd41e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
